language: cpp
os: linux
compiler: gcc 
sudo: required
services: docker

script: docker run -v imgag/ngs-bits:/mnt --name my_container ubuntu:16.04 && docker exec -it my_container ls /mnt/



#TODOs:
# - also test clang compiler