language: cpp
os: linux
compiler: gcc 
sudo: required
services: docker


script:
 - docker run --privileged -v $TRAVIS_BUILD_DIR:/root/ngs-bits ubuntu:16.04 /bin/bash -c "apt-get update && apt-get -y install qt5-default libqt5xmlpatterns5-dev libqt5sql5-mysql git cmake python python-matplotlib && cd /root/ngs-bits/ && make build_3rdparty build_tools_release test_lib test_tools"



#TODOs:
# - also test clang compiler