language: cpp
os: linux
compiler: gcc 
sudo: required
services: docker

script:
  - docker run -t -v $TRAVIS_BUILD_DIR:/mnt:Z --name my_container ubuntu:16.04
  - docker exec my_container /mnt/tools/TravisCI/build.sh



#TODOs:
# - also test clang compiler